version: '3'
services:
  postgres:
    image: postgres:latest
  web-app:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - '8080:80'
    restart: on-failure
    container_name: web-app
  to-do-api:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - '3001:3001'
    restart: on-failure
    container_name: to-do-api
    volumes:
      - /app/node_modules # Inside the container, don't try to override this folder, just leave as is
      - ./server:/app # Look at the server directory and copy everything into the app folder in the container
    environment:
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=
      - PGPORT=5432
